# =============================================
# CONFIGURACION DEL SERVIDOR
# =============================================
server.port=8080
spring.application.name=hotel-sistema
# =============================================
# CONEXION A ORACLE CLOUD ATP - WALLET
# Usuario: ADMIN
<<<<<<< HEAD
# Wallet: C:\lenguajes\Wallet_ProyectoLenguajes
# =============================================
spring.datasource.url=jdbc:oracle:thin:@proyectolenguajes_high
spring.datasource.username=ADMIN
spring.datasource.password=Mathiewanthuan.21
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Wallet path
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=C:\\lenguajes\\Wallet_ProyectoLenguajes
spring.datasource.hikari.data-source-properties.oracle.net.wallet_location=(SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=C:\\lenguajes\\Wallet_ProyectoLenguajes)))

=======
# Service: proyectolenguajes_high
# Wallet: C:\lenguajes\Wallet_ProyectoLenguajes.zip
# =============================================
spring.datasource.url=jdbc:oracle:thin:@proyectolenguajes_high?TNS_ADMIN=C:/Lenguajes/Wallet_ProyectoLenguajes
spring.datasource.username=ADMIN
spring.datasource.password=Mathiewanthuan.21
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
>>>>>>> origin/feature/persona3_sp_ReporteVentasProductos
# Connection pool
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
<<<<<<< HEAD

=======
>>>>>>> origin/feature/persona3_sp_ReporteVentasProductos
# =============================================
# THYMELEAF
# =============================================
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
# =============================================
# SEGURIDAD
# =============================================
spring.security.user.name=admin_default
spring.security.user.password=disabled_use_db
# =============================================
# LOGGING
# =============================================
logging.level.com.hotel=DEBUG
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=DEBUG